name: Github Page React Deploy Workflow

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn build
        env:
          CI: ""
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
          
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
